import React from 'react';

import {StyleSheet} from 'react-native';
export const screenBackground = '#F9F9F9';
export const white = '#FFFFFF';
export const borderColor = '#9ED5E3';
export const titleColor = '#2D2D2D';
export const grey = '#B7B7B7';
export const blackColor = '#000000';
export const blue = '#9ED5E3';
export const dardAccent = '#C5A7CF';
export const lightAccent = '#CDA0D9';
export const black = 'FilsonProBlack-Black';
export const book = 'FilsonProBook-Book';
export const Regular = 'FilsonProRegular-Regular';
export const Heavy = 'FilsonProHeavy-Heavy';
export const light = 'FilsonProLight-Light';
export const medium = 'FilsonProMedium-Medium';
export const extraBold = 'HKGrotesk-ExtraBold';
export const semiBoldLegecy = 'HKGrotesk-SemiBoldLegacy';
export const semiBold = 'HKGrotesk-SemiBold';
export const RegularLegecy = 'HKGrotesk-RegularLegacy';
